version: "3"
services:
  app:
    build: .
    depends_on:
    - postgres
    ports:
    - "3000:3000"
    - "9229:9229"
    - "8080:8080"

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
