version: "3"
services:
  app:
    build: .
    links:
    - postgres
    depends_on:
    - postgres
    environment:
      APP_NAME: game-20
      PORT: 3000
      PG_HOST: localhost
      PG_PORT: 35432
      PG_USERNAME: leke
      PG_PASSWORD: lekeleke
      PG_DATABASE: game-20
      PG_TABLE_SESSION: session
      PG_TABLE_QUESTION: question
    ports:
    - "3000:3000"
    volumes:
    - ./api/:/api/
    - ./client/:/client/

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: leke
      POSTGRES_PASSWORD: lekeleke
      POSTGRES_DB: game-20
    ports:
    - "35432:5432"
    volumes:
    - ./database:/var/lib/postgresql/data
